import sys,os

mydir = os.path.dirname(sys.argv[0])
if len(mydir) == 0: mydir = "./"

template = open(mydir + '/htaccess-template','r').read()

issuers = list()
users = list()

if len(sys.argv) == 2:
    if sys.argv[1] == '-':
        input = sys.stdin
    else:
        input = open(sys.argv[1],'r')
elif len(sys.argv) == 1:
     input = open('/var/lib/vsroom/certificates/allowed.csv')
else:
    print 'Usage: %s <input file>' % os.path.basename(sys.argv[0])


for line in input.readlines():
    line = line.strip()
    if line.startswith("#"):
        continue
    try:
        sanitized_user, raw_user, issuer = line.split(";")
    except ValueError:
        print "Warning: the following line should have exactly two ; delimiters:"
        print ' ' + line
        sys.exit(1)
        
    issuers.append(issuer)
    users.append(raw_user)

issuers.sort()
users.sort()
print "# This file is autogenerated with %s" % (sys.argv[0])
print template

if len(issuers) == 0:
    issuers.append('No issuers defined.')

if len(users) == 0:
    users.append('No users defined.')

sys.stdout.write('SSLRequire %%{SSL_CLIENT_I_DN_OU} eq \"%s\"' % (issuers.pop()))
while len(issuers) > 0:
    sys.stdout.write(' or \\\n %%{SSL_CLIENT_I_DN_OU} eq \"%s\"' % (issuers.pop()))
print '\n'

sys.stdout.write('SSLRequire %%{SSL_CLIENT_S_DN} eq \"%s\"' % (users.pop()))
while len(users) > 0:
    user = users.pop()
    user = user.replace("\\","\\\\")
    sys.stdout.write(' or \\\n %%{SSL_CLIENT_S_DN} eq \"%s\"' % (user))

print ''

